# Generated by Django 5.2.4 on 2025-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="age",
            field=models.CharField(
                choices=[("kid", "0-14"), ("young", "15-20"), ("idk", "21-999")],
                default="kid",
                max_length=5,
            ),
        ),
    ]
