# Generated by Django 5.2.4 on 2025-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_question_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "Easy"), ("Normal", "Normal"), ("Hảd", "Hảd")],
                max_length=10,
            ),
        ),
    ]
