# Generated by Django 5.2.4 on 2025-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_question_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Quiz", [("MC", "Multi-choice"), ("SC", "Single-choice")]),
                    ("Text", [("FT", "Filling-text"), ("WA", "Write-answer")]),
                    ("Other", "Other"),
                ],
                default="SC",
                max_length=20,
            ),
        ),
    ]
